"""
Configuration package.
Exports all config variables for backward compatibility during migration.
"""

from config.engine import Timeframe, TIMEFRAME_WINDOWS, EPSILON, MOMENTUM_SMOOTHING
from config.indices import SECTOR_TICKERS, BENCHMARKS, DEFAULT_BENCHMARK, DEFAULT_TIMEFRAME
from config.cache import (
    PROJECT_ROOT, DATA_DIR, CACHE_DAILY_DIR, CACHE_WEEKLY_DIR, CACHE_MONTHLY_DIR, LOG_DIR,
    PERIOD_DAYS, CACHE_FRESHNESS_HOURS, MAX_RETRIES, RETRY_BASE_DELAY, DATA_PROVIDER
)
from config.animation import ANIMATION_INTERVAL_MS, ANIMATION_MIN_SPEED_MS, ANIMATION_MAX_SPEED_MS
from config.ui import QUADRANT_COLORS, QUADRANT_BG_OPACITY, TAIL_LENGTH

__all__ = [
    "Timeframe", "TIMEFRAME_WINDOWS", "EPSILON", "MOMENTUM_SMOOTHING",
    "SECTOR_TICKERS", "BENCHMARKS", "DEFAULT_BENCHMARK", "DEFAULT_TIMEFRAME",
    "PROJECT_ROOT", "DATA_DIR", "CACHE_DAILY_DIR", "CACHE_WEEKLY_DIR", "CACHE_MONTHLY_DIR", "LOG_DIR",
    "PERIOD_DAYS", "CACHE_FRESHNESS_HOURS", "MAX_RETRIES", "RETRY_BASE_DELAY", "DATA_PROVIDER",
    "ANIMATION_INTERVAL_MS", "ANIMATION_MIN_SPEED_MS", "ANIMATION_MAX_SPEED_MS",
    "QUADRANT_COLORS", "QUADRANT_BG_OPACITY", "TAIL_LENGTH"
]
